const constants = {
	SET_SCREEN: 		'SET_SCREEN',
	SET_EVENT_KEYS:		'SET_EVENT_KEYS',
	RESET_EVENT_KEYS:	'RESET_EVENT_KEYS',
	SET_CONTEXT: 		'SET_CONTEXT',
	SET_GAME_STATE:		'SET_GAME_STATE',
	SET_GAME_SOUND:		'SET_GAME_SOUND',
	SET_GAME_LANG:		'SET_GAME_LANG',

	SET_ASTEROID_COUNT:	'SET_ASTEROID_COUNT',
	SET_POWERUP_COUNT:	'SET_POWERUP_COUNT',
	SET_ENEMY_COUNT:	'SET_ENEMY_COUNT',
	SET_TIME_VALUE:		'SET_TIME_VALUE',

	SET_ASTEROIDS_DESTROYED:	'SET_ASTEROIDS_DESTROYED',
	SET_ENEMIES_DESTROYED:		'SET_SET_ENEMIES_DESTROYED',
	SET_BULLETS_FIRED:			'SET_BULLETS_FIRED',
	SET_BULLETS_HIT:			'SET_BULLETS_HIT',
	SET_POWERUP_USAGE:			'SET_POWERUP_USAGE',
	SET_SHIELD_USAGE:			'SET_SHIELD_USAGE',
	SET_CURRENT_SHIELD:			'SET_CURRENT_SHIELD',
	SET_CURRENT_LIFE:			'SET_CURRENT_LIFE',
	SET_CURRENT_SCORE:			'SET_CURRENT_SCORE',
	SET_TOP_SCORE_IN_USE:		'SET_TOP_SCORE_IN_USE',
	SET_TOP_SCORE_CLASSIC:		'SET_TOP_SCORE_CLASSIC',
	SET_TOP_SCORE_SPACERACE:	'SET_TOP_SCORE_SPACERACE',
	SET_TOP_SCORE_BATTLE:		'SET_TOP_SCORE_BATTLE'
}

export default constants
